### ISSUE TITLE
Bildexport für SCAD Datei möglich?

### ISSUE THREAD

**Issue by D33pWat3r** [benjaminht/spacetable#1]
könnte man zusätzliche Export Dateien zur Verfügung stellen, um den aktuellen Entwurf zu sehen?
Also z.B. ein Bild?

**Comment by 24367dfa** [comment]
Das STL würde schon reichen, GitHub rendert das direkt in der Weboberfläche.

**Comment by D33pWat3r** [comment]
oder so :)
ich benutze nur kein SCAD und wollte mir das zum anschauen nicht extra unterladen (wie viele andere bestimmt auch)
